[project]
name = "rusty-element"
version = "0.1.0"
dependencies = ["cffi"]

[tool.maturin]
python-source = "python"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "maturin"

[tool.black]
preview = true