name: 🧪 Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests-rust:
    name: Run tests (Rust)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: ["stable", "beta", "nightly"]
    steps:
      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}
      - uses: actions/checkout@v2
      - name: Style checks
        run: |
          cd rust
          rustup component add rustfmt
          cargo fmt -- --check
      - name: Build rust library
        run: |
          cd rust
          cargo build
          cargo build --release
      - name: Run tests
        run: |
          cd rust
          cargo test
  run-tests-python:
    name: Run tests (Python)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install test requirements
        run: pip3 install pytest flake8
      - name: Style checks
        run: flake8 python/
      - name: Install Python library
        run: |
          pip3 install setuptools-rust
          cd python
          pip3 install .
      - name: Run tests
        run: python3 -m pytest .
